services:
  - type: web
    name: stock-analysis-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5 